version: "3.8"

services:

  quarkus-postgresql:
    container_name: quarkus-postgres
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
        - 5432:5432
    networks:
      - quarkus-net

  quarkus-app:
    build:
      context: .  # Use o diretório atual como contexto (onde o Dockerfile está localizado)
    ports:
        - 8080:8080
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-postgresql:5432/postgres
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    networks:
      - quarkus-net

networks:
  quarkus-net:
    driver: bridge