
     create table if not exists usuarios (
            id int8 generated by default as identity,
            email varchar(255),
            nome varchar(255),
            cpf varchar(255),
            senha varchar(255),
            status boolean,
            created_at timestamp not null,
            updated_at timestamp not null,
            primary key (id)
        );

